name: Run tests for self-hosted github runner

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  test-runner-arm64:
    runs-on: [linux, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Architecture
        run: uname -a

      - name: Check User
        run: whoami && id

      - name: Check Disk Space
        run: df -h

      - name: Hello World
        run: echo "Hello from the self-hosted runner!"

  test-runner-x64:
    runs-on: [linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Architecture
        run: uname -a

      - name: Check User
        run: whoami && id

      - name: Check Disk Space
        run: df -h

      - name: Hello World
        run: echo "Hello from the self-hosted runner!"
